### ISSUE TITLE
Allowing "pipe" notation in Jinja snippets

### ISSUE THREAD

**Issue by Mierdin** [StackStorm/st2mistral#31]
https://github.com/StackStorm/st2mistral/pull/30 introduces most of the filter functions that were previously only available in StackStorm/ActionChains.

However, as discussed in https://github.com/StackStorm/st2/pull/3565#discussion_r130012137, the way the function is called changes the parameters that are passed to it. This is in large part due to the way that Mistral leverages `functools.partial`, so the right solution would be to fix this upstream. In the meantime, Jinja snippets in Mistral workflows **must** use the function format (i.e. no pipe operators) in order to function correctly (the functions will assume the first positional arg is the context)

Once the issue is addressed in Mistral, we should:

- [ ] Update docs, removing the restriction on the way filters are used in Jinja in Mistral
- [ ] Add test with two snippets, one with each format - and ensure they're equivalent

```yaml
version: '2.0'

examples.mistral-test-function-vs-filter:
    description: A basic workflow for testing differences in function call format
    type: direct
    input:
        - input_str
        - regex_pattern
    output:
        result_jinja_1: <% $.result_jinja_1 %>
        result_jinja_2: <% $.result_jinja_2 %>
    tasks:

        task1:
            action: std.noop
            publish:

                result_jinja_1: '{{ _.input_str | regex_match(_.regex_pattern)}}'
                result_jinja_2: '{{ regex_match(_.input_str, _.regex_pattern)}}'

```

```python
class TestFunctionVsFilter(base.TestWorkflowExecution):

    def test_function_vs_filter(self):

        execution = self._execute_workflow(
            'examples.mistral-test-function-vs-filter',
            parameters={
                "input_str": "567 Elsewhere Dr is my address",
                "regex_pattern": "([0-9]{3} \\w+ (?:Ave|St|Dr))"
            }
        )
        execution = self._wait_for_completion(execution)
        self._assert_success(execution, num_tasks=1)
        self.assertTrue(execution.result['result_jinja_1'])
        self.assertTrue(execution.result['result_jinja_2'])
        self.assertEqual(execution.result['result_jinja_1'], 
                         execution.result['result_jinja_2'])
```
