### ISSUE TITLE
Exception is not raised for invalid st2 key

### ISSUE THREAD

**Issue by jinpingh** [StackStorm/st2mistral#39]
st2 3.0.0, on Python 2.7.6

Expected result: If a key doesn't exist, exception should be raised. 
Right now since HTTP returns 201 for a invalid key, https://github.com/StackStorm/st2mistral/blob/master/st2mistral/functions/stackstorm.py#L82 exception is not raised.

Simple workflow to duplicate issue:
```
---
description: >
    A sample workflow that demonstrates st2kv usage
enabled: true
name: mistral-st2kv
pack: examples
runner_type: mistral-v2
entry_point: workflows/mistral-st2kv.yaml
```
```
version: '2.0'

examples.mistral-st2kv:
  tasks:
    task1
      action: core.local
      input:
        cmd: 'echo "{{ st2kv.system.foo}}"'
```
